import Modal from '@/components/modal'
import './globals.css'
import type { Metadata } from 'next'
//import { Inter } from 'next/font/google'

//const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Trillo ai',
  description: 'Generated by Mokhtar Tarek',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#F5F6F8]' >{children}</body>
      <Modal />
    </html>
  )
}
